name: spoinkstore
version: '1.0'
summary: Spoink OS's Store
description: Spoink OS's Store
grade: stable
confinement: strict

apps:
  spoinkstore:
    command: desktop-launch $SNAP/spoinkstore
    environment:
      QML2_IMPORT_PATH: "$QML2_IMPORT_PATH:$SNAP/usr/qml"
    plugs:
      - network
      - home
      - removable-media

parts:
  spoinkstore:
    plugin: qmake
    source: .
    build-packages:
      - qtbase5-dev
      - libqt5network5
      - libqt5widgets5
      - qtbase5-dev-tools  # Added for development tools
    stage-packages:
      - libqt5network5
      - libqt5widgets5
      - libqt5multimedia5  # Add more packages as needed

    after: [desktop/qt5]
    override-build: |
      make INSTALL_ROOT=$SNAPCRAFT_PART_INSTALL install

    build-environment:
      - |
        export LIBS+=" -L$SNAPCRAFT_PART_INSTALL/lib"
        export LIBS+=" -L$SNAPCRAFT_PART_INSTALL/usr/lib"
        export LIBS+=" -L$SNAPCRAFT_PART_INSTALL/lib/x86_64-linux-gnu"
        export LIBS+=" -L$SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu"
        export INCLUDEPATH+=" -I$SNAPCRAFT_PART_INSTALL/usr/include"

  desktop/qt5:
    plugin: nil
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
