name: spoinkstore
version: '0.1'
summary: SpoinkStore GTK App
description: GTK application for managing snaps

grade: stable
confinement: strict

apps:
  spoinkstore:
    command: spoinkstore
    plugs: [home, network, x11]
    desktop: spoinkstore.desktop

parts:
  spoinkstore:
    source: .
    plugin: autotools
    build-packages:
      - build-essential
      - gtk-doc-tools
      - libgtk-3-dev
      - libjson-glib-dev
    stage-packages:
      - libgtk-3-0
      - libjson-glib-1.0-0
