name: spoinkstore
version: '1.0'
summary: Spoink OS's Store
description: Spoink OS's Store
grade: stable
confinement: strict

apps:
  spoinkstore:
    command: spoinkstore
    plugs:
      - network
      - home
      - removable-media

parts:
  spoinkstore:
    plugin: make
    source: .
    build-packages:
      - libcurl4-openssl-dev  # Add other necessary build packages
    stage-packages:
      - libcurl4  # Add other necessary runtime packages
