name: spoinkstore
version: '1.0'
summary: Spoink OS's Store
description: Spoink OS's Store
grade: stable
confinement: strict

apps:
  spoinkstore:
    plugs:
      - network
      - home
      - removable-media

parts:
  spoinkstore:
    plugin: make
    source: .
    build-packages:
      - libgtk-3-dev
      - libjson-glib-dev

    after: [desktop/gtk]

  desktop/gtk:
    plugin: nil
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
