name: spoinkstore
version: '1.0'
summary: Spoink OS's Store
description: |
  Spoink OS's Store

grade: stable
confinement: strict

apps:
  spoinkstore:
    command: desktop-launch $SNAP/spoinkstore
    plugs:
      - network
      - home
      - removable-media

parts:
  spoinkstore:
    plugin: qmake
    source: .
    build-packages:
      - qtbase5-dev
      - libqt5network5
      - libqt5widgets5
    stage-packages:
      - libqt5network5
      - libqt5widgets5
